/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package pkg.app;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int man=0x7f020001;
        public static final int splash=0x7f020002;
        public static final int truck=0x7f020003;
    }
    public static final class id {
        public static final int login=0x7f050003;
        public static final int mv=0x7f050004;
        public static final int ucell=0x7f050002;
        public static final int umail=0x7f050000;
        public static final int upass=0x7f050001;
    }
    public static final class layout {
        public static final int login=0x7f030000;
        public static final int map=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int hint4cell=0x7f040004;
        public static final int hint4mail=0x7f040002;
        public static final int hint4pass=0x7f040003;
        public static final int loginText=0x7f040001;
    }
}
